### ISSUE TITLE
How can I toast the Hijri date

### ISSUE THREAD

**Issue by freebumba27** [sahaab/HijriCalendar-master#1]
On clicking on the date it's showing the Georgian Calendar date. I want to show Hijri date. How to do that?

**Comment by sahaab** [comment]
please use this function
HijriCalendarDate.getSimpleDate(Calendar.getInstance(),"0")
to get the hijri date for that calendar Date instance

**Comment by sahaab** [comment]
please use this function
HijriCalendarDate.getSimpleDate(Calendar.getInstance(),"0")
to get the hijri date for that calendar Date instance

**Comment by freebumba27** [comment]
``` Java

@Override
public void onSelectDate(Date date, View view) {
Toast.makeText(getApplicationContext(), HijriCalendarDate.getSimpleDate(Calendar.getInstance(), 0), Toast.LENGTH_SHORT).show();
}
```

I am trying this but it's always giving today's Hijri date as toast. How can I get selected Hijri Date

**Comment by sahaab** [comment]
Please wait a moment, i will construct the code for you and send you it

Assalamu Alaikum,
Sahaab Zahid

**Comment by freebumba27** [comment]
That will be really helpful.

**Comment by sahaab** [comment]
``` Java
public static Calendar DateToCalendar(Date date){ 
  Calendar cal = Calendar.getInstance();
  cal.setTime(date);
  return cal;
}

@Override
public void onSelectDate(Date date, View view) {
    Toast.makeText(getApplicationContext(),
         HijriCalendarDate.getSimpleDate(DateToCalendar(date), 0),
         Toast.LENGTH_SHORT).show();
}
```

**Comment by freebumba27** [comment]
Work like charm.. Thanks
I have modified little bid, It looks like this - 

``` Java
@Override
public void onSelectDate(Date date, View view) {
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    Toast.makeText(getApplicationContext(), HijriCalendarDate.getSimpleDate(cal, 0), Toast.LENGTH_SHORT).show();
}
```

**Comment by sahaab** [comment]
No problem :D , glad to help
and yep that is fine, if you like, you may email me your app when you are done, I would love to see it inshaAllah :D

**Comment by freebumba27** [comment]
It have modified couple of things It's look like this.
![screenshot_2015-07-14-12-02-22](https://cloud.githubusercontent.com/assets/12707934/8667686/535335c0-2a20-11e5-8840-b96acfbdddd2.png)
