### ISSUE TITLE
Is there any way to use Activity instead of FragmentActivity 

### ISSUE THREAD

**Issue by freebumba27** [sahaab/HijriCalendar-master#2]
`CaldroidSampleActivity extends FragmentActivity`

Is there any way to use 
`CaldroidSampleActivity extends Activity`

I am getting error on this like `getSupportFragmentManager()`

`dialogCaldroidFragment.restoreDialogStatesFromKey(getSupportFragmentManager(), state,"DIALOG_CALDROID_SAVED_STATE", dialogTag);`

**Comment by sahaab** [comment]
its built to use FragmentActivity :-/ wud require quite a bit of changes

**Comment by freebumba27** [comment]
ok I understand...
